# Generated by Django 6.0 on 2026-01-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketIndicatorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[("KR", "Korea"), ("US", "United States")],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("KOSPI", "KOSPI"),
                            ("KOSDAQ", "KOSDAQ"),
                            ("NASDAQ", "NASDAQ"),
                            ("SP500", "S&P 500"),
                            ("VIX", "VIX"),
                            ("USDKRW", "USD/KRW"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "market", "key"],
                        name="markets_mar_date_4015b4_idx",
                    )
                ],
                "unique_together": {("market", "key", "date")},
            },
        ),
        migrations.CreateModel(
            name="MarketRankSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[("KR", "Korea"), ("US", "United States")],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("KOSPI", "KOSPI"),
                            ("KOSDAQ", "KOSDAQ"),
                            ("NASDAQ", "NASDAQ"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("INTRADAY", "Intraday"), ("EOD", "End of Day")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "rank_type",
                    models.CharField(
                        choices=[
                            ("MARKET_CAP", "Market Cap"),
                            ("VOLUME", "Volume"),
                            ("GAINERS", "Gainers"),
                            ("LOSERS", "Losers"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("rows", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "exchange", "kind"],
                        name="markets_mar_date_59d33a_idx",
                    )
                ],
                "unique_together": {("exchange", "date", "kind", "rank_type")},
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[("KR", "Korea"), ("US", "United States")],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("currency", models.CharField(default="KRW", max_length=8)),
                (
                    "exchange",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KOSPI", "KOSPI"),
                            ("KOSDAQ", "KOSDAQ"),
                            ("NASDAQ", "NASDAQ"),
                        ],
                        db_index=True,
                        default="",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["market", "exchange"],
                        name="markets_sto_market_f221c1_idx",
                    ),
                    models.Index(
                        fields=["market", "is_active"],
                        name="markets_sto_market_d7d86e_idx",
                    ),
                ],
                "unique_together": {("market", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="IntradayStockSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "last_price",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "prev_close",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "intraday_pct",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("volume", models.BigIntegerField(null=True)),
                ("traded_value", models.BigIntegerField(null=True)),
                ("market_cap", models.BigIntegerField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intraday_snapshots",
                        to="markets.stock",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "stock"], name="markets_int_date_ecea22_idx"
                    ),
                    models.Index(
                        fields=["date", "intraday_pct"],
                        name="markets_int_date_7e6464_idx",
                    ),
                    models.Index(
                        fields=["date", "volume"], name="markets_int_date_35c8a0_idx"
                    ),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
        migrations.CreateModel(
            name="EodStockSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "open",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "high",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "low",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "prev_close",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("market_cap", models.BigIntegerField(null=True)),
                ("volume", models.BigIntegerField(null=True)),
                ("traded_value", models.BigIntegerField(null=True)),
                (
                    "volatility_20d",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eod_snapshots",
                        to="markets.stock",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "stock"], name="markets_eod_date_475c10_idx"
                    ),
                    models.Index(
                        fields=["date", "market_cap"],
                        name="markets_eod_date_d06a9b_idx",
                    ),
                    models.Index(
                        fields=["date", "change_pct"],
                        name="markets_eod_date_d9bf95_idx",
                    ),
                    models.Index(
                        fields=["date", "volume"], name="markets_eod_date_c5d691_idx"
                    ),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
