# Generated by Django 6.0 on 2026-01-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStockSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "open",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "prev_close",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "intraday_pct",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("market_cap", models.BigIntegerField(null=True)),
                ("volume", models.BigIntegerField(null=True)),
                (
                    "volatility_20d",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="eodstocksnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="eodstocksnapshot",
            name="markets_eod_date_475c10_idx",
        ),
        migrations.RemoveIndex(
            model_name="eodstocksnapshot",
            name="markets_eod_date_d06a9b_idx",
        ),
        migrations.RemoveIndex(
            model_name="eodstocksnapshot",
            name="markets_eod_date_d9bf95_idx",
        ),
        migrations.RemoveIndex(
            model_name="eodstocksnapshot",
            name="markets_eod_date_c5d691_idx",
        ),
        migrations.AlterUniqueTogether(
            name="intradaystocksnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="intradaystocksnapshot",
            name="markets_int_date_ecea22_idx",
        ),
        migrations.RemoveIndex(
            model_name="intradaystocksnapshot",
            name="markets_int_date_7e6464_idx",
        ),
        migrations.RemoveIndex(
            model_name="intradaystocksnapshot",
            name="markets_int_date_35c8a0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="marketindicatorsnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="marketindicatorsnapshot",
            name="markets_mar_date_4015b4_idx",
        ),
        migrations.DeleteModel(
            name="MarketIndicatorSnapshot",
        ),
        migrations.AlterUniqueTogether(
            name="marketranksnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="marketranksnapshot",
            name="markets_mar_date_59d33a_idx",
        ),
        migrations.DeleteModel(
            name="MarketRankSnapshot",
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="markets_sto_market_f221c1_idx",
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="markets_sto_market_d7d86e_idx",
        ),
        migrations.AlterField(
            model_name="stock",
            name="exchange",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="dailystocksnapshot",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="markets.stock",
            ),
        ),
        migrations.RemoveField(
            model_name="eodstocksnapshot",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="intradaystocksnapshot",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="updated_at",
        ),
        migrations.AddIndex(
            model_name="dailystocksnapshot",
            index=models.Index(
                fields=["date", "stock"], name="markets_dai_date_0098e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystocksnapshot",
            index=models.Index(
                fields=["date", "market_cap"], name="markets_dai_date_7942eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystocksnapshot",
            index=models.Index(
                fields=["date", "intraday_pct"], name="markets_dai_date_f1f5a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystocksnapshot",
            unique_together={("stock", "date")},
        ),
        migrations.DeleteModel(
            name="EodStockSnapshot",
        ),
        migrations.DeleteModel(
            name="IntradayStockSnapshot",
        ),
    ]
