# Generated by Django 6.0 on 2026-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_dailystocksnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="dailystocksnapshot",
            index=models.Index(
                fields=["date", "change_pct"], name="markets_dai_date_14d042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["market", "exchange"], name="markets_sto_market_f221c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["exchange", "symbol"], name="markets_sto_exchang_450d98_idx"
            ),
        ),
    ]
