# Generated by Django 6.0 on 2026-01-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0003_stock_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asof_date", models.DateField(db_index=True)),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("KOSPI", "KOSPI"),
                            ("KOSDAQ", "KOSDAQ"),
                            ("NASDAQ", "NASDAQ"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "ranking_type",
                    models.CharField(
                        choices=[
                            ("MARKET_CAP", "시가총액"),
                            ("RISE", "상승률"),
                            ("FALL", "하락률"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("rank", models.PositiveIntegerField(db_index=True)),
                ("symbol_code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("trade_price", models.FloatField(blank=True, null=True)),
                ("change_rate", models.FloatField(blank=True, null=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="dailystocksnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="dailystocksnapshot",
            name="markets_dai_date_0098e2_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailystocksnapshot",
            name="markets_dai_date_7942eb_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailystocksnapshot",
            name="markets_dai_date_f1f5a5_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailystocksnapshot",
            name="markets_dai_date_14d042_idx",
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="markets_sto_market_f221c1_idx",
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="markets_sto_exchang_450d98_idx",
        ),
        migrations.AddIndex(
            model_name="dailyrankingsnapshot",
            index=models.Index(
                fields=["asof_date", "market", "ranking_type", "rank"],
                name="markets_dai_asof_da_c2c88d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyrankingsnapshot",
            index=models.Index(
                fields=["asof_date", "market", "ranking_type"],
                name="markets_dai_asof_da_fec1d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyrankingsnapshot",
            index=models.Index(
                fields=["symbol_code", "asof_date"],
                name="markets_dai_symbol__747109_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyrankingsnapshot",
            unique_together={("asof_date", "market", "ranking_type", "rank")},
        ),
        migrations.DeleteModel(
            name="DailyStockSnapshot",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
