# Generated by Django 6.0 on 2026-01-07 13:50

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("analysis", models.JSONField(blank=True, null=True)),
                ("url", models.URLField(max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("published_at", models.DateTimeField()),
                ("market", models.CharField(max_length=50)),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                ("sector", models.CharField(blank=True, max_length=50, null=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
    ]
