# Generated by Django 6.0 on 2026-01-16 15:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("published_at", models.DateTimeField(db_index=True)),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("Korea", "Korea"),
                            ("International", "International"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                ("sector", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("SEMICONDUCTOR_AI", "Semiconductor/AI"),
                            ("BATTERY", "Battery"),
                            ("ENERGY", "Energy"),
                            ("FINANCE_HOLDING", "Finance/Holding"),
                            ("ICT_PLATFORM", "ICT/Platform"),
                            ("BIO_HEALTH", "Bio/Health"),
                            ("AUTO", "Auto"),
                            ("ETC", "ETC"),
                        ],
                        db_index=True,
                        default="ETC",
                        max_length=30,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["market", "-published_at"],
                        name="news_newsar_market_174e10_idx",
                    ),
                    models.Index(
                        fields=["theme", "-published_at"],
                        name="news_newsar_theme_23f169_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsArticleAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Lv1"),
                            (2, "Lv2"),
                            (3, "Lv3"),
                            (4, "Lv4"),
                            (5, "Lv5"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("SEMICONDUCTOR_AI", "Semiconductor/AI"),
                            ("BATTERY", "Battery"),
                            ("ENERGY", "Energy"),
                            ("FINANCE_HOLDING", "Finance/Holding"),
                            ("ICT_PLATFORM", "ICT/Platform"),
                            ("BIO_HEALTH", "Bio/Health"),
                            ("AUTO", "Auto"),
                            ("ETC", "ETC"),
                        ],
                        db_index=True,
                        default="ETC",
                        max_length=30,
                    ),
                ),
                ("analysis", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="news.newsarticle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["article", "level"],
                        name="news_newsar_article_92f78a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "level"), name="uniq_article_level"
                    )
                ],
            },
        ),
    ]
