# Generated by Django 6.0 on 2026-01-10 14:27

import django.core.validators
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("analysis", models.JSONField(blank=True, null=True)),
                ("url", models.URLField(max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("published_at", models.DateTimeField()),
                ("market", models.CharField(max_length=50)),
                (
                    "related_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("SEMICONDUCTOR_AI", "반도체 / AI"),
                            ("BATTERY", "배터리 (2차전지)"),
                            ("GREEN_ENERGY", "원자력 / 친환경에너지"),
                            ("FINANCE_HOLDING", "금융 / 지주사"),
                            ("ICT_PLATFORM", "정보통신 / 플랫폼"),
                            ("BIO_HEALTH", "바이오 / 헬스케어"),
                            ("AUTO", "자동차"),
                            ("SHIPBUILDING", "조선"),
                            ("ETC", "기타"),
                        ],
                        db_index=True,
                        default="ETC",
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
    ]
