# Generated by Django 6.0 on 2026-01-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticleAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Lv1"),
                            (2, "Lv2"),
                            (3, "Lv3"),
                            (4, "Lv4"),
                            (5, "Lv5"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("SEMICONDUCTOR_AI", "Semiconductor/AI"),
                            ("BATTERY", "Battery"),
                            ("GREEN_ENERGY", "Green Energy"),
                            ("FINANCE_HOLDING", "Finance/Holding"),
                            ("ICT_PLATFORM", "ICT/Platform"),
                            ("BIO_HEALTH", "Bio/Health"),
                            ("AUTO", "Auto"),
                            ("ETC", "ETC"),
                        ],
                        db_index=True,
                        default="ETC",
                        max_length=30,
                    ),
                ),
                ("analysis", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="analysis",
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="theme",
            field=models.CharField(
                choices=[
                    ("SEMICONDUCTOR_AI", "Semiconductor/AI"),
                    ("BATTERY", "Battery"),
                    ("GREEN_ENERGY", "Green Energy"),
                    ("FINANCE_HOLDING", "Finance/Holding"),
                    ("ICT_PLATFORM", "ICT/Platform"),
                    ("BIO_HEALTH", "Bio/Health"),
                    ("AUTO", "Auto"),
                    ("ETC", "ETC"),
                ],
                db_index=True,
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="market",
            field=models.CharField(
                choices=[("Korea", "Korea"), ("International", "International")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["market", "-published_at"], name="news_newsar_market_174e10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["theme", "-published_at"], name="news_newsar_theme_23f169_idx"
            ),
        ),
        migrations.AddField(
            model_name="newsarticleanalysis",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="news.newsarticle",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticleanalysis",
            index=models.Index(
                fields=["article", "level"], name="news_newsar_article_92f78a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsarticleanalysis",
            constraint=models.UniqueConstraint(
                fields=("article", "level"), name="uniq_article_level"
            ),
        ),
    ]
