# Generated by Django 6.0 on 2026-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
