# Generated by Django 6.0 on 2026-01-11 07:26

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle",
            name="embedding",
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="embedding_local",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="market",
            field=models.CharField(
                choices=[("KR", "국내"), ("INTERNATIONAL", "해외")],
                db_index=True,
                default="KR",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
