# Generated by Django 6.0 on 2025-12-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('KR', 'Korea'), ('US', 'United States')], db_index=True, max_length=2)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('exchange', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'unique_together': {('market', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='DailyStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('prev_close', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('change_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('intraday_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('volatility_20d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='main.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'stock'], name='main_dailys_date_27a675_idx'), models.Index(fields=['date', 'market_cap'], name='main_dailys_date_411d4f_idx'), models.Index(fields=['date', 'intraday_pct'], name='main_dailys_date_fc9ef7_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
