# Generated by Django 6.0 on 2026-01-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_chat_sessions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="main_chatme_session_86e09e_idx",
            old_name="main_chatme_session_3d0f3a_idx",
        ),
    ]
