# Generated by Django 6.0 on 2026-01-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
    ]
