# Generated by Django 6.0 on 2026-01-03 02:09

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_app', '0002_auto_20260103_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('market', models.CharField(max_length=10)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
    ]
