# Generated by Django 6.0 on 2026-01-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
