# Generated by Django 6.0 on 2026-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_newsarticle_content_alter_newsarticle_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
