# Generated by Django 6.0 on 2026-01-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThemePickDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("KR", "Korea"),
                            ("US", "United States"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("theme", models.CharField(max_length=80)),
                ("symbol", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("reason", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["date", "scope"], name="reco_themep_date_8934ac_idx"
                    ),
                    models.Index(
                        fields=["scope", "updated_at"],
                        name="reco_themep_scope_47ea55_idx",
                    ),
                ],
                "unique_together": {("date", "scope", "rank")},
            },
        ),
    ]
