# Generated by Django 6.0 on 2026-01-17 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrendKeywordDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("KR", "Korea"), ("US", "United States")],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("keyword", models.CharField(max_length=80)),
                ("reason", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["date", "scope"], name="reco_trendk_date_e84d53_idx"
                    ),
                    models.Index(
                        fields=["scope", "updated_at"],
                        name="reco_trendk_scope_e95539_idx",
                    ),
                ],
                "unique_together": {("date", "scope", "rank")},
            },
        ),
        migrations.CreateModel(
            name="TrendKeywordNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("content", models.TextField(blank=True, default="")),
                ("link", models.URLField(db_index=True, max_length=1000)),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "published_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("needs_image_gen", models.BooleanField(db_index=True, default=False)),
                ("analysis_full", models.JSONField(blank=True, null=True)),
                (
                    "analyzed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="reco.trendkeyworddaily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrendKeywordNewsAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(db_index=True)),
                ("analysis", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="reco.trendkeywordnews",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["trend", "created_at"], name="reco_trendk_trend_i_63cb29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["needs_image_gen", "created_at"],
                name="reco_trendk_needs_i_16dc20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["analyzed_at", "created_at"],
                name="reco_trendk_analyze_57b366_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnewsanalysis",
            index=models.Index(
                fields=["news", "level"], name="reco_trendk_news_id_25f768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnewsanalysis",
            index=models.Index(
                fields=["level", "updated_at"], name="reco_trendk_level_67c33e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trendkeywordnewsanalysis",
            unique_together={("news", "level")},
        ),
    ]
