# Generated by Django 6.0 on 2026-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendKeywordDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("KR", "Korea"),
                            ("US", "United States"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("keyword", models.CharField(max_length=80)),
                ("reason", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["date", "scope"], name="reco_trendk_date_e84d53_idx"
                    ),
                    models.Index(
                        fields=["scope", "updated_at"],
                        name="reco_trendk_scope_e95539_idx",
                    ),
                ],
                "unique_together": {("date", "scope", "rank")},
            },
        ),
    ]
