# Generated by Django 6.0 on 2026-01-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0002_trendkeyworddaily"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendKeywordNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True, default="")),
                ("link", models.URLField(db_index=True, max_length=1000)),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "published_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("needs_image_gen", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="themepickdaily",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="themepickdaily",
            name="reco_themep_date_8934ac_idx",
        ),
        migrations.RemoveIndex(
            model_name="themepickdaily",
            name="reco_themep_scope_47ea55_idx",
        ),
        migrations.DeleteModel(
            name="ThemePickDaily",
        ),
        migrations.AlterField(
            model_name="trendkeyworddaily",
            name="scope",
            field=models.CharField(
                choices=[("KR", "Korea"), ("US", "United States")],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="trendkeywordnews",
            name="trend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_items",
                to="reco.trendkeyworddaily",
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["trend", "created_at"], name="reco_trendk_trend_i_63cb29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["needs_image_gen", "created_at"],
                name="reco_trendk_needs_i_16dc20_idx",
            ),
        ),
    ]
