# Generated by Django 6.0 on 2026-01-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0003_trendkeywordnews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendkeywordnews",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="trendkeyworddaily",
            name="scope",
            field=models.CharField(
                choices=[("KR", "Korea"), ("US", "United States")],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="trendkeywordnews",
            name="summary",
            field=models.TextField(),
        ),
    ]
