# Generated by Django 6.0 on 2026-01-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0004_trendkeywordnews_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendkeywordnews",
            name="related_stock_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="trendkeywordnews",
            name="related_stock_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
