# Generated by Django 6.0 on 2026-01-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0005_trendkeywordnews_related_stock_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trendkeywordnews",
            name="related_stock_code",
        ),
        migrations.RemoveField(
            model_name="trendkeywordnews",
            name="related_stock_name",
        ),
    ]
