# Generated by Django 6.0 on 2026-01-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0006_remove_trendkeywordnews_related_stock_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendkeywordnews",
            name="analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trendkeywordnews",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["updated_at"], name="reco_trendk_updated_34aabd_idx"
            ),
        ),
    ]
