# Generated by Django 6.0 on 2026-01-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reco", "0006_remove_trendkeywordnews_related_stock_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendKeywordNewsAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(db_index=True)),
                ("analysis", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.AddField(
            model_name="trendkeywordnews",
            name="analysis_full",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trendkeywordnews",
            name="analyzed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnews",
            index=models.Index(
                fields=["analyzed_at", "created_at"],
                name="reco_trendk_analyze_57b366_idx",
            ),
        ),
        migrations.AddField(
            model_name="trendkeywordnewsanalysis",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="reco.trendkeywordnews",
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnewsanalysis",
            index=models.Index(
                fields=["news", "level"], name="reco_trendk_news_id_25f768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendkeywordnewsanalysis",
            index=models.Index(
                fields=["level", "updated_at"], name="reco_trendk_level_67c33e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trendkeywordnewsanalysis",
            unique_together={("news", "level")},
        ),
    ]
